#!/bin/bash

LOCAL_APP_URL=localhost:8080
REMOTE_APP_URL=http://wof-spring-boot-test-env.eba-is45gqj2.ca-central-1.elasticbeanstalk.com

echo Using local app:
curl ${LOCAL_APP_URL}/count
echo
curl ${LOCAL_APP_URL}/percentage/I%20in%20ICA%2CC%2CSecond%20A%20in%20AMERICA%27S
echo
echo
echo Using remote app:
curl ${REMOTE_APP_URL}/count
echo
curl ${REMOTE_APP_URL}/percentage/I%20in%20ICA%2CC%2CSecond%20A%20in%20AMERICA%27S
